name: Unit tests

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  javascript-test:
    name: JavaScript Tests

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install JavaScript dependencies
        run: npm ci

      - name: Run JavaScript tests
        run: npm test

  python-test:
    name: Python Tests

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: python3 -m pip install pytest

      - name: Run Python tests
        run: python3 -m pytest
